Fix token

diff --git a/.github/actions/check-if-package-has-published/action.yml b/.github/actions/check-if-package-has-published/action.yml
--- a/.github/actions/check-if-package-has-published/action.yml
+++ b/.github/actions/check-if-package-has-published/action.yml
@@ -19,8 +19,8 @@ runs:
         NODE_AUTH_TOKEN: ${{ inputs.token }}
       id: check-publish-status
       run: |
-        npm view ${{ inputs.name }} --json 2>/dev/null | tee /tmp/npm-view.json
-        PUBLISHED=`cat /tmp/npm-view.json | jq -r 'if .error then if .error.code == "E404" then false else halt_error(1) end else true end'` && true || exit 1
+        npm view ${{ inputs.name }}@{{ inputs.version }} --json 2>/dev/null | tee /tmp/output.json
+        PUBLISHED=`cat /tmp/output.json | jq -r 'if .error then if .error.code == "E404" then false else halt_error(1) end else true end'` && true || exit 1
 
         echo published=$PUBLISHED >> $GITHUB_OUTPUT
       shell: bash
