Set default shell and remove set -euo

diff --git a/.github/actions/check-if-package-has-published/action.yml b/.github/actions/check-if-package-has-published/action.yml
--- a/.github/actions/check-if-package-has-published/action.yml
+++ b/.github/actions/check-if-package-has-published/action.yml
@@ -20,11 +20,8 @@ runs:
     - env:
         NODE_AUTH_TOKEN: ${{ inputs.token }}
       id: check-publish-status
-      run: set -euo pipefail && npm view --json ${{ inputs.registry-url && format('--registry={0}', inputs.registry-url) }} ${{ inputs.name }}@${{ inputs.version }} 2>/dev/null | tee /tmp/output.json || true
+      run: npm view --json ${{ inputs.registry-url && format('--registry={0}', inputs.registry-url) }} ${{ inputs.name }}@${{ inputs.version }} 2>/dev/null | tee /tmp/output.json || true
       shell: bash
     - id: result
-      run: |
-        set -euo pipefail
-
-        echo published=`cat /tmp/output.json | jq -r 'if .error then if .error.code == "E404" then false else halt_error(1) end else true end'` | tee --append $GITHUB_OUTPUT
+      run: echo published=`cat /tmp/output.json | jq -r 'if .error then if .error.code == "E404" then false else halt_error(1) end else true end'` | tee --append $GITHUB_OUTPUT
       shell: bash
