Halt error

diff --git a/.github/workflows/continuous-deployment-matrix.yml b/.github/workflows/continuous-deployment-matrix.yml
--- a/.github/workflows/continuous-deployment-matrix.yml
+++ b/.github/workflows/continuous-deployment-matrix.yml
@@ -377,7 +377,7 @@ jobs:
       - env:
           GH_TOKEN: ${{ github.token }}
         name: Publish release
-        run: gh release edit --draft=false --json --prerelease ${{ env.publish-tag }} --repo ${{ github.repository }}
+        run: gh release edit --draft=false --prerelease ${{ env.publish-tag }} --repo ${{ github.repository }}
 
   github-pages-deploy:
     environment:
@@ -437,7 +437,7 @@ jobs:
       - id: package-existence
         name: Check if package already present
         run: |
-          EXIST=`npm view ${{ steps.prepare.outputs.package-id }} --json 2>/dev/null | jq -r 'if .error then if .error.code == "E404" then false else "error" end else true end'` && true || exit 1
+          EXIST=`npm view ${{ steps.prepare.outputs.package-id }} --json 2>/dev/null | jq -r 'if .error then if .error.code == "E404" then false else halt_error(1) end else true end'` && true || exit 1
 
           echo exist=$EXIST >> $GITHUB_OUTPUT
       - env:
